baseURL: "https://xzebra.dev/"
title: Zebra
paginate: 5
theme: PaperMod

enableEmoji: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

outputs:
    home:
      - HTML
      - RSS
      - JSON

taxonomies:
  category: categories
  series: series
  tag: tags

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Zebra
  description: "Blog about programming projects, CTFs and games development."
  keywords: [portfolio, blog, zebra]
  author: xzebra
  # author: ["Me", "You"] # multiple authors
  images: ["/images/banner.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: true

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  hideFooter: true
  showtoc: false
  tocopen: false

  # Hidden categories in the blog general list
  hiddenCategories: 
    - "hackthebox"

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/images/favicon.ico"
    favicon16x16: "/images/favicon-16x16.png"
    favicon32x32: "/images/favicon-32x32.png"
    apple_touch_icon: "/images/apple-touch-icon.png"
    # safari_pinned_tab: "/images/favicon.png"

  label:
    text: "Zebra"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Zebra
    subtitle: "Software developer"
    # imageUrl: "/images/author/zebra.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    # buttons:
    #   - name: Posts
    #     url: posts
    #   - name: Tags
    #     url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: github 
      url: "https://www.github.com/xzebra"
    - name: email
      url: "mailto:contact@xzebra.dev"
    - name: hackthebox
      url: "https://app.hackthebox.eu/users/680488"
    - name: codesignal
      url: "https://app.codesignal.com/profile/xzebra"
    - name: linkedin
      url: "https://www.linkedin.com/in/jorge-romanos"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page
    linkFullImages: false
    responsiveImages: false


  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "description"]
menu:
  main:
    - identifier: home
      name: home
      url: /
      weight: 10
    - identifier: blog
      name: blog
      url: /blog/
      weight: 20
    - identifier: series
      name: series
      url: /series/
      weight: 30
    - identifier: search
      # name: search
      name: 🔍
      url: /search/
      weight: 40
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
